
version: 2

jobs:
  deploy:
    working_directory: ~/Jxnet
    docker:
      - image: 'circleci/openjdk:8-jdk'
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: 'export TERM=xterm-color'
      - run: 'sudo apt-get update && sudo apt-get install gcc libpcap-dev gnupg -y'
      - run: 'echo "githubToken=$GITHUB_TOKEN" >> gradle.properties'
      - run: 'echo "bintrayUser=$BINTRAY_USER" >> gradle.properties'
      - run: 'echo "bintrayPass=$BINTRAY_PASS" >> gradle.properties'
      - run: 'echo "sonatypeUser=$SONATYPE_USER" >> gradle.properties'
      - run: 'echo "sonatypePass=$SONATYPE_PASS" >> gradle.properties'
      - run: 'echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties'
      - run: 'echo "signing.password=$SIGNING_PASS" >> gradle.properties'
      - run: 'echo "signing.secretKeyRingFile=/tmp/secring.gpg" >> gradle.properties'
      - run: 'gpg --batch --yes --passphrase=$SIGN_KEY --output /tmp/secring.gpg --decrypt --cipher-algo AES256 ./gradle/resources/gpg/secring.gpg.enc'
      - run: './gradlew dependencyCheckAnalyze --no-daemon -q'
      - run: './gradlew clean build install bintrayUpload dist github -x test --no-daemon -q'
      - save_cache:
          key: gradle
          paths:
            - "~/.gradle"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - v1
